name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          sshpass -p 'Halion2012' \
            ssh -o StrictHostKeyChecking=no -l ubuntu ec2-18-237-116-245.us-west-2.compute.amazonaws.com 'cd /home/ubuntu/changeMoneyAPI && git pull origin main && nvm use 16 && npm install && pm2 restart backend'
        env:
          SSHPASS: Halion2012
