name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "Iniciando despliegue..."
          sshpass -p 'LA_CLAVE_' \
            ssh -o StrictHostKeyChecking=no -l ubuntu ec2-18-237-116-245.us-west-2.compute.amazonaws.com '
              echo "Ingresando al directorio..." &&
              cd /home/ubuntu/changeMoneyAPI &&
              echo "Actualizando repositorio..." &&
              git pull origin main &&
              source ~/.nvm/nvm.sh &&
              nvm use 16 &&
              export PATH=$PATH:~/.nvm/versions/node/v16.19.0/bin &&
              echo "Instalando dependencias..." &&
              npm install &&
              echo "Reiniciando servidor..." &&
              pm2 restart backend'
        env:
          SSHPASS: LA_CLAVE
