name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          sshpass -p 'Halion2012' \
            ssh ubuntu@ec2-18-237-116-245.us-west-2.compute.amazonaws.com 'cd /path/to/your/app/changeMoneyAPI && git pull origin main && npm install && npm run restart'
        env:
          SSHPASS: Halion2012
